### PR TITLE
Add Qt 6.4 builds

### PR DESCRIPTION
**Pull request by Nerixyz**
Thank you for the builds! I want to use the macOS artifacts for https://github.com/SevenTV/chatterino7/pull/245. We're currently on Qt 5.15.2 and Qt 6.5.0, so I'm adding a build for the 6.5.0 version. With 6.6 being around the corner, maybe a build for that version should be added as well if it's not binary compatible to 6.5/6.4.

### CODE REVIEW

**Comment by jurplel** [comment]
Can you change the rule in the yml to try running it?

I would like to confirm that all of the binaries are built successfully. It should hopefully be fine but sometimes changing the Qt version breaks things.

Also, just want to say I am very happy that someone else is getting some value out of my ~weeks of labor setting this annoying thing up.

**Comment by Nerixyz** [comment]
> Can you change the rule in the yml to try running it?

Sure!

**Comment by jdpurcell** [comment]
I think you'll encounter [QTBUG-110134](https://bugreports.qt.io/browse/QTBUG-110134) trying to build QtApng on 6.5.0; it failed for me [on 6.5.3](https://github.com/jdpurcell/kimageformats-binaries/actions/runs/6338924009/job/17218001180) at least. I ended up leaving it on Qt 6.4.3.

**Comment by jurplel** [comment]
Sorry for the delay—running CI

**Comment by jurplel** [comment]
All looks good on these builds (thankfully), but I am not sure if there is much point in keeping QtApng and KImageFormats at separate versions, since you presumably want to use both for your deployment. (I assume you can't use plugins built with 6.4 with programs built with 6.5, correct me if I am wrong)

Someone should probably update QtApng to fix this bug. In a cruel twist of fate, my fork of QtApng (with some of @jdpurcell's changes, as well) is the most up-to-date version.

In the meantime, maybe qt 6.4 for kimageformats is okay?

**Comment by Nerixyz** [comment]
> Someone should probably update QtApng to fix this bug.

I got a build with CMake working, gonna PR that later. I'm not sure if I _need_ to update the dependencies yet.

> In the meantime, maybe qt 6.4 for kimageformats is okay?

Totally fine with me. Technically, they should be binary compatible, but I haven't tried yet. 

---

I can squash the commits if you want to.

**Comment by jurplel** [comment]
Great, thank you!

**Pull request merged**
